### ISSUE TITLE
Plugins classpathPrefix are pointing to the wrong path

### ISSUE THREAD

**Issue by cabralfortiss** [arrowhead-f/core-java#14]
Running on a Windows 10 machine

I ran "mvn clean install" and got the generated jar file. But when trying to execute them, trough scripts or directly, I get the error that the main class is missing. After some reasearch, the problem was actually that the libraries weren't found. In all pom.xml files, the classpathPrefix is set as 

`<classpathPrefix>../lib/</classpathPrefix>`

but if I change them to

`<classpathPrefix>./lib/</classpathPrefix>`

it works. This is because, I assume, the lib folder is in the same level as my jar file.

I got already a patch on my fork 
https://github.com/cabralfortiss/core-java/commit/d4b47b011fb24759d690b3a5dff0b2a4079043d6
that could be merged, altough there are still some "../lib" in the debian-packages documentation and in the swager stuff that I'm not sure if it's related to this

**Comment by uzoltan** [comment]
I did this change 5 days ago in this commit: https://github.com/arrowhead-f/core-java/commit/25393725374e31e6292db342faa547c818061c60#diff-b6ee57ca080a2272749664e87fc807b7

To be honest I just followed the instructions of the developer, who created the debian package generation, it did not register with me, that this would brake a normal maven installed setup. I'll revert the classpathPrefix back, and see what I have to change to make the debian package generation work with it. Thanks for noticing the bug.

**Comment by uzoltan** [comment]
I pushed a commit which might have solved the issue (meaning the classpath works both on normal maven install and debian package install too): https://github.com/arrowhead-f/core-java/commit/fd0735ca8ff72e7ade85f1337b8e5f4112e30d2c

I will test it later today.

**Comment by cabralfortiss** [comment]
Pull and tested on my local machine and it worked. Feel free to close the issue when you tested

**Comment by uzoltan** [comment]
I'll close it if works on linux systems too, using the debian package generator.
