### ISSUE TITLE
Problems with password protected databases

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/core-java#20]
Just realised (when trying MySQL 8) that the Debian packages do not like that the MySQL root user is password protected...

**Comment by eudyptula** [comment]
Thinking that all scripts (but the ah_db_user function) should use the arrowhead user and the password we generate.

The ah_db_user function should ask (once!) for the root password for creating the arrowhead user.

**Comment by uzoltan** [comment]
> The ah_db_user function should ask (once!) for the root password for creating the arrowhead user.

I think that's a fine solution. I'll keep open this issue, until it is implemented.

**Comment by susnye** [comment]
This requirement shall be included in the install documentation

**Comment by eudyptula** [comment]
Should be solved in develop branch now - Zoltan, could you please confirm that it works for you also?

**Comment by uzoltan** [comment]
I tested the latest code on Ubuntu server and it worked. 

1 **small thing** to note is that setting a root password after the mysql installation is the easiest via the provided `sudo mysql_secure_installation` script, which at the very least demands database passwords to be 8 character or longer. This concerns the password for the arrowhead user too, so if during install the cloud operator gives a short password, the install will fail with 

> Your password does not satisfy the current policy requirements

and the packages need to be purged, and try again.
