### ISSUE TITLE
MySQL Connection Security

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/core-java#21]
Currently, we're using `useSSL=false&allowPublicKeyRetrieval=true` in the MySQL connector string. This opens for potential vulnerabilities to consider. See https://mysql-net.github.io/MySqlConnector/connection-options/

**Comment by uzoltan** [comment]
Can you tell me why those are necessary in the connection string? When testing on Windows, I dont need either of these. What happens when you do not provide those on debian?

**Comment by eudyptula** [comment]
I added the latter recently - maybe caused my MySQL 8. Can't remember, I'll retry and give you the error message ;)

**Comment by eudyptula** [comment]
MySQL 5.x & Oracle Java 8... OK
MySQL 5.x & Oracle Java 11... OK
MySQL 8.x & OpenJDK... OK

Hmm, weird :S - I guess that useSSL=false was something with the old connector version, and setting that to false required allowPublicKeyRetrieval=true on some of the newer versions. Removing both seems to work all all three combinations above.

Pull request #25 should do the trick...
