### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by eudyptula** [arrowhead-f/core-java#23]
I have a development machine on CET with application systems and a server on UTC with the core systems. The result was errors with events being set to far in the future. Guessing that it is a timezone issue.

Noticed that LocalDateTime is used in the code and not ZonedDateTime. Tried changing it, but ran into some missing validators (think it was within hibernate).

**Comment by uzoltan** [comment]
I will look into changing the event timestamp to ZonedDateTime

**Comment by uzoltan** [comment]
6223fe36e0fc827b3993c78402eb4b749511976c
