### ISSUE TITLE
Documentation bug in Temperature Provider

### ISSUE THREAD

**Issue by jenseliasson** [arrowhead-f/core-java#43]
The example message in the IDD has incorrect time information and unit according to the SenML specification. The unit is "Cel" and the t field should have a value of 0.
File: Arrowhead IndoorTemperature Service IDD.docx
Path: core-java/documentation/Application Systems/Temperature/

**Comment by uzoltan** [comment]
fixed in d6b84ab0fa27c883e781a202be27ab9a4c12eefe
