### ISSUE TITLE
Query with wrong interface still returns services

### ISSUE THREAD

**Issue by cabralfortiss** [arrowhead-f/core-java#44]
I'm not sure about the right behaviour, but I registered a service with interface JSON, but if I query the service with interface "JSON1" or no interface at all "", the Service Registry still returns the registered service. Is this the right behaviour?

**Comment by uzoltan** [comment]
Right now I'm pretty sure interface matching happens on the side of the Orchestrator. Tomorrow I'll check if this could be moved to the SR, or it's this way for a reason.

**Comment by uzoltan** [comment]
I even had a //NOTE above the interface filtering in the Orchestrator code, that I think this should be done on the SR side, so now I've moved it there :) 

e1173fcfeef4d72c4cd6db1c1618c5827c2db8d3

**Comment by cabralfortiss** [comment]
Just tested! Works fine!

**Comment by uzoltan** [comment]
Btw the matching is **case sensitive.**
