### ISSUE TITLE
InboundDebugFilter throws exception for incoming request not convertable to JSON format

### ISSUE THREAD

**Issue by jaivgar** [arrowhead-f/core-java#51]
When creating a service that would consume a MediaType.MULTIPART_FORM_DATA, and executing the system created with the -d option, the incoming request throwed an IOException during JSON serialization: ![Datamanager_response_error](https://user-images.githubusercontent.com/44204948/55316877-a3ef9000-546f-11e9-8d91-d421efe09260.png)

To avoid the JSON serialization I modified the code in the InboundDebugFilter class like:
```Java
if (requestContext.getMediaType() == MediaType.APPLICATION_JSON_TYPE) {
    	  String prettyJson = Utility.getRequestPayload(requestContext.getEntityStream());
          System.out.println(prettyJson);

          InputStream in = new ByteArrayInputStream(prettyJson.getBytes("UTF-8"));
          requestContext.setEntityStream(in);
}
else {
    	  // Specify actions for other MediaTypes
}
```

It was enough for my case but I review could bring a better solution to improve visualization at the command line.

**Comment by eudyptula** [comment]
I actually manage to find a better solution than checking the media type manually, however this does require a full update to Log4j 2.x.

Fixed in branch: https://github.com/arrowhead-f/core-java/tree/feature/common%2Blog4j2
